// app/layout.tsx

import { ReactNode } from 'react';

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header>Header</header>
        {children}
        
        <footer>Footer</footer>
        </body>
    </html>
  );
}
